### ISSUE TITLE
Whitelist needs more granularity

### ISSUE THREAD

**Issue by mxhenry-godaddy** [godaddy/tartufo#2]
ISBAT: define down to the line and column of the file whether to ignore a violation. Current implementation of ignoring an entire file is too broad.

**Comment by tarkatronic** [comment]
I've had ideas swimming around in my head off and on for this, and I think some of the recent developments can help with this. The idea I had amounts to a `tartufo.toml` which would look something like this:

```toml
[tool.tartufo]
entropy = true
regex = true
json = true

[[tool.tartufo.whitelist]]
signature = "4fb147a685e9d1cce323e87f7692cca361ede6b3:tartufo/scanner.py:27:Entropy:"

[[tool.tartufo.whitelist]]
signature = "5eef3cb7a93ebc28f56324ff695743250fe53cab:tests/test_config.py:21:RegEx:RSA private key 2"
```

The breakdown of that whitelist line is: `<commit hash>:<filename>:<line number>:<scan type>:<optional: scan type detail>`
This is not terribly difficult for humans to consume, and is easily machine generated, so we could have something like `tartufo --create-whitelist` (or if #39 happens, then `tartufo create-whitelist`)

These could also optionally be made more verbose, something like:

```toml
[[tool.tartufo.whitelist]]
commit_hash = "5eef3cb7a93ebc28f56324ff695743250fe53cab"
filename = "tests/test_config.py"
line_number = 21
match_type = "RegEx"
match_detail = "RSA private key 2"
```

I think that's a bit excessive though, and would lead to far too verbose config files.

Either way, this would give us an internal data structure like this: https://github.com/toml-lang/toml#array-of-tables.

The main catch here would be, since the commit hash is included, this will not help with pre-commit scans. So in `tartufo` itself for an example, we need to be able to commit some code which looks like it contains secrets, but is in fact just tests or regexes looking for the secrets. Currently, I have to work around this by doing `git commit -n`. Perhaps that's okay for now?

**Comment by tarkatronic** [comment]
Additional nit: We should do away with the `blacklist`/`whitelist` nomenclature. They're just not great.

**Comment by decompil3d** [comment]
I think that the approach that @rscottbailey suggested would be great! It's easier to implement than a machine-generated file and it allows an ignore to persist across commits, which you probably want (for example, you add a SHA to a file, then ignore it, and wouldn't want to be nagged at the next commit to that file).

If you want, the hash could be:

```
hash(offendingString + filePath)
```

I leave out commit SHA for the aforementioned reason and I leave out line number since that may change as the file is updated. Furthermore, scan type isn't needed since it's unlikely to change -- if a string is flagged by Entropy once, it'll probably always be flagged by Entropy.

**Comment by tarkatronic** [comment]
Looking back at this again I think that's the right way to go. I had been thinking of how to allow an exclusion across commits and was thinking of making the commit hash optional in the signature. But that really is over-complicating things.

I would like to push for keeping these in the config file though. Maybe just in a list? I'll have to think more on the best format. So they would look something like:

```toml
[tool.tartufo]
entropy = true
regex = true
json = true
exclusions = [
    'b5fe98cf91552287c844ad566d6b8ec1f049da00eabf4873fab5da68b56c8e59',  # password = 'foobar'$$test/test_login.py
    '5e227153befa12d41c2920eab82b3261a2dac918031b21bdc086c296128ba310',  # https://github.com/godaddy/tartufo/commit/e2406699cf00fe31abbf496e96f87da5ebda3c5c$$CHANGELOG.md
]
```

As a note, not necessarily important here just yet, those were generated with the [BLAKE2](http://blake2.net/) hashing algorithm, which is available in Python's stdlib, due largely to its speed.

Any thoughts on this as an implementation, @decompil3d @rscottbailey?
