### ISSUE TITLE
Deprecate `--rules` in favor of `--rule-patterns`

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#256]
## Is your feature request related to a problem? Please describe.

At this point, all tartufo config has been moved into the one central configuration file, except for `--rules`. In order to keep everything consistent, we should fix this one last one.

## Describe the solution you'd like

* Use of the `--rules` option should present the user with a `DeprecationWarning`
* New regex patterns should instead be specified in the configuration file as a table of tables, similar to [new style entropy exclusion](https://tartufo.readthedocs.io/en/stable/features.html#entropy-limiting). It would probably look something like

    ```toml
    [tool.tartufo]
    rule-patterns = [
      {name = "Private key", pattern = "---- BEGIN EC PRIVATE KEY ----", path_pattern = "/some/path"}
    ]
    ```
    OR
    ```toml
    [[tool.tartufo.rule-patterns]]
    name = "Private key"
    pattern = "---- BEGIN EC PRIVATE KEY ----"
    path_pattern = "/some/path"
    ```
* Required keys would be "name" and "pattern"; "path_pattern" would be optional.

As far as the future deprecation path, I see two possibilities:

1. This gets added to `main` directly, then ported to the `v3.x` branch, with the `--rules` option removed entirely in v3.0
2. This gets merged into `v3.x`, and we decide upon some far future version (likely even v4.0) where the `--rules` option can be fully removed

The choice is up to the author of the PR!
