### ISSUE TITLE
Pre-commit hook: High entropy strings not detected in new files by 3.0.0

### ISSUE THREAD

**Issue by prajasekaran-godaddy** [godaddy/tartufo#331]
## 🐛 Bug Report

Tartufo 3.0.0 does not detect high entropy strings in files that are getting added to the index by the commit that is being evaluated.

## To Reproduce

1. Add/update pre-commit config file to use tartufo 3.0.0
```yaml
repos:
  - repo: https://github.com/godaddy/tartufo
    rev: v3.0.0
    hooks:
      - id: tartufo
        name: tartufo
        entry: tartufo
        args: [ pre-commit ]
        language: python
        pass_filenames: false
```
2. Install the pre-commit configuration
```bash
pre-commit install
```
3. Create a new file with high entropy string
4. Stage the file and commit it. Commit suceeeds
```bash
date | shasum > new_file.txt
git add new_file.txt
git commit -m "committing a high entropy string"
```

## Expected Behavior

Commit should not succeed, and return failure. (2.10.0 rejects the commit as expected)

## Environment

1. Macintosh
2. Installed pre-commit through pip (2.17.0)
