### ISSUE TITLE
File Extension-based Matching

### ISSUE THREAD

**Issue by dclayton-godaddy** [godaddy/tartufo#88]
## Is your feature request related to a problem? Please describe.

To detect literal passwords in files like YAML, JSON, JS, etc require different matching.

Examples:

* yaml: `password: mypassword`
* json: `"password": "mypassword"`
* js: `{password: 'mypassword'}`

## Describe the solution you'd like

Add the file extension to regexs file.

```yaml
- message: contains a password or token
  match: '(password|passwd|pwd|token|pass)(["])?[=:]'
  conditions:
    - file: '*.js'
      match: '(password|passwd|pwd|token|pass)([''" \t]*)[=:]([ \t]*)(([''"][^''"])|([\[]))'
    - file: '*.json'
      match: '(password|passwd|pwd|token|pass)([''" \t]*)[=:]([ \t]*)(([''"][^''"])|([\[]))'
    - file: '*.py'
      match: '(password|passwd|pwd|token|pass)([''" \t]*)[=:]([ \t]*)(([''"][^''"])|([\[]))'
```
